name: Latest book list from a goodreads
on:
  schedule: # Run workflow automatically
    # This will make it run twice a day (06:00 and 18:00)
    - cron: "0 6,18 * * *"
    # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
  workflow_dispatch:
jobs:
  update-readme-with-goodreads-books:
    name: Update this repo's README with goodreads books
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: zwacky/goodreads-profile-workflow@main

        with:
          goodreads_user_id: "77882125"
          shelf: "currently-reading"
          template: "- [$title]($url) by $author ($my_rating_stars)"
